# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - bddnewsapitest

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)
  # AZURE_SUBSCRIPTION_ID: "d1e8559b-d8d5-4b6b-9337-2e334a125b53"
#  AZURE_CLIENT_ID: "88c333da-f62c-43fb-b0ab-47eef8892726"
#  AZURE_CLIENT_SECRET: "dwD8Q~NFtbi3LxvU7MtZzm2GHx4gtleSl5Nf~csO"
 # AZURE_TENANT_ID: "3f3eba09-badc-486c-8592-b7449bebd373"
  
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
    #  - name: Install Azure CLI
    #    run: |
    #      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    #  - name: Log in to Azure
    #    run: |
   #       az login --service-principal -u ${{ env.AZURE_CLIENT_ID }} -p ${{ env.AZURE_CLIENT_SECRET }} --tenant ${{ env.AZURE_TENANT_ID }}
 
             
   #   - name: Set Azure subscription
   #     run: |
   #         az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}
      

      # Add more steps here to execute Azure CLI commands

     # - name: Example Azure CLI command
    #    run: az storage account list

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Azure Login
        uses: azure/login@v1
      - name: Install dependencies
        uses: azure/functions-action@v1
        with:
            app-name: your-function-app-name
            package: ${{ github.workspace }}/Severeweather/requirements.txt
      #  run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'demo-testing-functionapp'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BF8ABE3B2746410D988A28527FFA4DB2 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
